base/urls.py
from django.conf.urls import *


urlpatterns = patterns('',
    url(r'^json/$', 'base.views.client_json', name='client-json'),
    url(r'^add/$', 'base.views.client_add', name='client-add' ),
    url(r'^browse/$', 'base.views.client_browse', name='client-browse' ),
    url(r'^client-list/$', 'base.views.client_list', name='combo-client-list'), 
    url(r'^(?P<id>\d+)/$', 'sts.views.client_detail', name='client-detail'),
    url(r'^$', 'sts.views.client_list', name='client-list'),
    )

seq/urls.py
from django.conf.urls import *


urlpatterns = patterns('',
    #url(r'^seqsamples/$', 'seq.views.sequencing_samples', name='seq-sequencing-samples' ),
    #url(r'^flowcell/create/$', 'seq.views.flowcell_create', name='flowcell-create'),
    url(r'^flowcell/samplequeue/$', 'seq.views.sequence_sample_queue', name='sample-queue'),
    url(r'^flowcell/miseqsamplequeue/$', 'seq.views.miseq_sequence_sample_queue', name='myseq-sample-queue'),
    url(r'^flowcell/seqsamplequeuejson/$', 'seq.views.seq_sample_queue_json', name='sample-queue-json'),
    url(r'^spredsheet/$', 'seq.views.miseq_spedsheet', name='miseq-spredsheet'),
    url(r'^sequencing_calculation/$', 'seq.views.sequencing_calculation', name='sequencing-calculation'),
    url(r'^run/create/$', 'seq.views.flowcell_create', name='run-create'),
    url(r'^run/edit/(?P<key>[\w-]+)/$', 'seq.views.flowcell_edit', name='run-edit'),
    url(r'^run/browse/$', 'seq.views.run_browse', name='run-browse'),
    url(r'^sequencing/contact/(?P<id>[\d-]+)/$', 'seq.views.sequencingContactActivity', name='sequencing-contact-activity'),
    url(r'^sequencing/lab/(?P<id>[\d-]+)/$', 'seq.views.sequencingLabActivity', name='sequencing-lab-activity'),
    url(r'^run/(?P<key>[\w-]+)/$', 'seq.views.run_detail', name='run-detail'),
    url(r'^flowcell/browse/$', 'seq.views.flowcell_browse', name='flowcell-browse'),
    url(r'^flowcell/(?P<key>[\w-]+)/$', 'seq.views.flowcell_detail', name='flowcell-detail' ),
)

sts/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

import menus
menus.autodiscover()

from tastypie.api import Api
#from core import api as coreapi
from billing import api as billingapi

v1_api = Api(api_name='v1')
v1_api.register(billingapi.BatchMultiplierResource())
v1_api.register(billingapi.BaseCodeResource())

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^client/', include('base.urls')),
    #url(r'^submit/$', 'sample.views.submit', name='submit' ),
    url(r'^specimen-submit/$', 'sample.views.specimen_submit', name='specimen-submit' ),
    url(r'^ngsubmit/$', 'sample.views.nextgen_submit', name='nextgen-submit' ),
    url(r'^specPegination/$', 'sample.views.getSpecimenPaginatedData', name='getSpecimenPaginatedData' ),
    url(r'^libprep/', include('libprep.urls')),
    url(r'^seq/', include('seq.urls')),
    url(r'^samp/', include('sample.urls')),
    url(r'^analysis/', include('analysis.urls')),
    url(r'^billing/', include('billing.urls')),
    url(r'^fr/', include('frontend.urls')),
    url(r'^submission/browse/$', 'sample.views.submission_browse', name='submission-browse' ),
    url(r'^run/browse/$', 'seq.views.run_browse', name='run-browse'),
    url(r'^signin/$', 'django.contrib.auth.views.login', {
        'template_name': 'frontend/signin.html',
    }),
    url(r'^signout/$', 'django.contrib.auth.views.logout', {
        'next_page': '/signin/',
    }, name="signout"),
    url(r'^favicon\.ico$', 'django.views.generic.RedirectView', {'url': '/static/img/favicon.ico'}),
    url(r'^api/', include(v1_api.urls)),
    url(r'^$', 'base.views.dashboard', name='dashboard' ),
    url(r'^seq/flowcell_json$', 'seq.views.flowcell_json', name='flowcell-json'),
    url(r'^custom_report/', include('custom_report.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

base/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from core import models as coremodels
from localflavor.us.models import USStateField

class EmailImage(models.Model):
    name = models.SlugField(help_text='')
    image = models.ImageField(upload_to='emailimages/', help_text='')
    
    def __unicode__(self):
        return u'%s' % (self.name)
    
    @models.permalink
    def get_absolute_url(self):
        return ('emailimage-view', [str(self.id)])
        
class Department(coremodels.CoreModel):
    number = models.IntegerField(db_column='DEPT_NUMBER')
    name = models.CharField(max_length=255, blank=True, null=True, help_text='')
    #slug = AutoSlugField(populate_from=('name', 'number'), overwrite=True)
    
    def __unicode__(self):
        return u'%d' % (self.number,)
    
    @models.permalink
    def get_absolute_url(self):
        return ('department-view', [str(self.id)])
        
    class Meta:
        # get_latest_by = ""
        ordering = ['name', ]
        # unique_together(('',''), )
        # verbose_name_plural = ""
        pass


class LabAddress(coremodels.CoreModel):
    ADDRESS_TYPES = (
        ('billing', 'Billing'),
        ('shipping', 'Shipping'),
        ('mailing ', 'Mailing '),
    )
    lab = models.ForeignKey("Lab", related_name='addresses')
    street = models.CharField(max_length=255, help_text='')
    city = models.CharField(max_length=255, default="St. Louis", help_text='')
    state = USStateField(default="MO", help_text='')
    zipcode = models.CharField(max_length=20, help_text='')
    type = models.CharField(max_length=255, choices=ADDRESS_TYPES, default="billing", help_text='')
    primary = models.BooleanField(default=False, help_text='')
    publish = models.BooleanField(default=True, help_text='')

    def __unicode__(self):
        return u'%s %s, %s, %s' % (self.street, self.city, self.state, self.zipcode)
        
    class Meta(coremodels.CoreModel.Meta):
        # get_latest_by = ""
        # ordering = []
        # unique_together(('',''), )
        verbose_name_plural = "Addresses"

#LabAddress._meta.get_field('type')._choices = (
#        ('billing', 'Billing'), ('mailing', 'Mailing')
#        )


class Lab(coremodels.CoreModel):
    last_name = models.CharField(max_length=255 )
    first_name = models.CharField(max_length=255, blank=True, null=True )
    shortname = AutoSlugField(populate_from=('last_name', 'first_name'), unique=True)
    location = models.CharField(max_length=10, choices=(('internal', "Internal"), ('external', 'External')))
    institution = models.CharField(max_length=255, blank=True, null=True )
    campus_box = models.PositiveIntegerField(blank=True, null=True)
    department = models.ForeignKey(Department, blank=True, null=True)
    primary_contact = models.ForeignKey("Client", blank=True, null=True, related_name="lab_primary_set")
    
    def __unicode__(self):
        if (self.first_name is None):
            return u'%s' % str(self.last_name)
        else:
            return u'%s' % str(self.first_name +' ' + self.last_name)

    @models.permalink
    def get_absolute_url(self):
        return ('lab-detail', [str(self.id)])
        
    class Meta(coremodels.CoreModel.Meta):
        # get_latest_by = ""
        ordering = ['last_name', 'first_name']
        unique_together = ('last_name', 'first_name')
        # verbose_name_plural = ""
        pass

    def save(self, *args, **kwargs):
        if self.location == 'internal':
            for x in (self.campus_box, self.department):
                if not x: 
                    raise Exception("For internal labs, you must specify a campus_box and department")
        elif self.location == 'external':
            #for x in (self.city,self.state,self.zipcode,self.street):
                #if not x:
                    #raise ValidationError("For external labs, you must specify all address information.")
            pass

        super(Lab, self).save(*args, **kwargs)


class ActiveClientManager(models.Manager):
    def get_queryset(self):
        return super(ActiveClientManager, self).get_query_set().filter(person__user__is_active=True)

class Client(coremodels.PersonType):
    lab = models.ForeignKey(Lab, blank=True, null=True, help_text='')

    objects = models.Manager()
    active = ActiveClientManager()
        
    @models.permalink
    def get_absolute_url(self):
        return ('client-detail', [str(self.id)])

    def __unicode__(self):
        return u'%s [%s]' % (self.name, self.lab)
 
    class Meta(coremodels.PersonType.Meta):
        pass

class Employee(coremodels.PersonType):

    @models.permalink
    def get_absolute_url(self):
        return ('employee-detail', [str(self.id)])
    

theme/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.forms.models import modelform_factory
from base import models as basemodels 
from core import models as coremodels 
from django.contrib.admin.widgets import AdminFileWidget
from django.contrib.auth.models import User
import localflavor.us.forms as usforms 
from django.core import validators


class Simple(forms.Form):
    email = forms.EmailField(label="Your email address")


class ClientAddForm(forms.ModelForm):
    first_name = forms.CharField(label='First Name', error_messages={
                    "required": "Please enter the first name",
                })
    last_name = forms.CharField(label='Last Name', error_messages={
                    "required": "Please enter the last name",
                })
    email = forms.EmailField(error_messages={
                    "required": "Please enter the email address",
                })
    phone = usforms.USPhoneNumberField(error_messages={
                    "required": "Please enter the phone number",
                    "invalid": "Phone numbers must be in (CCC) XXX-XXX-XXXX format.",
                },
                help_text="(CCC) XXX-XXX-XXXX", widget=forms.TextInput(attrs={'maxlength': '10', 'size': '13'}))
    extension = forms.IntegerField(label="Country Code", required=False, initial="1", widget=forms.TextInput(attrs={'maxlength': '3', 'size': '3'}))
    lab = forms.ModelChoiceField(basemodels.Lab.objects.all(), empty_label="New Lab", required=False)

    is_client_pi = forms.BooleanField(label="Is Client PI?", required=False)

    class Meta:
        model = coremodels.Person
        exclude = ('email', 'gender', 'user')

    def clean(self):
	cd = self.cleaned_data
	if 'phone' in cd and cd['phone'] and not cd['extension']:
	    self._errors["phone"] = self.error_class(['Phone numbers must be in (CCC) XXX-XXX-XXXX format.'])
	return cd
	

class LabAddForm(forms.ModelForm):
    department = forms.IntegerField(label="Department Number", required=False)
    last_name = forms.CharField(label='PI Last Name',
                error_messages={"required": "Please enter the PI last name ",},
                help_text="""
For labs headed by a PI: "FIRSTNAME LASTNAME Lab"

For other "labs" (centers, businesses): use the official name.
    """)
    first_name = forms.CharField(label='PI First Name', required=False)
    email = forms.EmailField(label="PI Email", error_messages={
                    "required": "Please enter the email address",
                })
    location = forms.ChoiceField(choices=(('','---------'),('internal', "Internal"), ('external', 'External')),
                        error_messages={"required": "Please select the lab's location.",},)
    
    class Meta:
        model = basemodels.Lab
        exclude = ('primary_contact', 'department')

    def save(self, *args, **kwargs):
        lab = super(LabAddForm, self).save(*args, commit=False, **kwargs)
        if self.cleaned_data['location'] == 'internal':
            lab.department = basemodels.Department.objects.get_or_create(number=self.cleaned_data['department'])[0]
        lab.save()
        return lab

    def clean(self):
        cd = self.cleaned_data
        if 'last_name' in cd and (basemodels.Lab.objects.filter(last_name=cd['last_name'], first_name=cd['first_name']).count() > 0):
            raise forms.ValidationError("PI Name is already in use'")
         
        if 'location' in cd and cd['location'] == 'internal':
            for x in ('department', 'campus_box'):
                if x in cd and not cd[x]:
                    self._errors[x] = self.error_class(['Internal labs must specify a %s.' % x,])
        if 'location' in cd and cd['location'] == 'external':
            if 'institution' in cd and not cd['institution']:
                self._errors['institution'] = self.error_class(['External labs must specify the institution.'])
        return cd

class BaseLabAddressFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseLabAddressFormSet, self).__init__(*args, **kwargs)
        self.forms[0].empty_permitted = False

LabAddressFormset = inlineformset_factory(basemodels.Lab, basemodels.LabAddress, extra=1, max_num=2, formset=BaseLabAddressFormSet, fields='__all__')

theme/views.py
# Create your views here.

theme/templates/base/client-browse.html
{% extends "sts/base.html" %}

{% block js %}
{{ block.super }}
<script type="text/javascript">
$(function() {
  $('table').dataTable({
    "bServerSide": true,
    "sAjaxSource": "",
    "aoColumns": [{ bSortable: true },{ bSortable: true },{ bSortable: false}] ,
  });
});
</script>
{% endblock js %}

{% block content %}
<h1>Browse Clients</h1>
<table>
<thead>
<tr>
<th>Name</th>
<th>Lab</th>
<th>Email</th>
</tr>
</thead>
<tbody>
</tbody>
<tfoot></tfoot>
</table>
{% endblock content %}

theme/templates/base/client_add.html
{% extends "sts/base.html" %}
{%load static from staticfiles %}

{% block css %}
{{ block.super }}
<style>
    table tr th:first-child, table tr td:nth-child(2) {
        width: 150px;
    }
    table th {
        font-weight: bold;
    }
    .column-left {
        width: {% if is_ajax_request %} 99% {% else %} 65% {% endif %}
    }
    .location {
        padding: 5px;
    }
</style>
{% endblock css %}

{% block js %}
{{ block.super }}
<script type="text/javascript">
    var labs = {{ labs }}
    
    function choose_lab() {
        $('#campus, #dept').hide();
        var val = $("#id_person-lab option:selected").val()
        if ( val == ''){
            $('#field_lab .last').html('')
            $('.new-lab').show();
            $("#id_person-is_client_pi").change();
            check_lab_location();
        } else {
            $('.new-lab').hide();
            if(labs[val]) {
                $('#campus td:eq(0)').html(labs[val][0]);
                $('#dept td:eq(0)').html(labs[val][1]);
                $('#field_lab .last').html('Internal')
                $('#campus, #dept').show();
            }else {
                $('#field_lab .last').html('External')
            }
        }
    }

    function check_lab_location() {
        var val = $('#id_lab-location').val();
        $(".content-box").addClass("column-left");
        $('.internal, .external').hide();
        
        if (val == 'internal') {
            $(".internal").show();
        } else if (val == 'external') {
            $(".external").show();
            $(".content-box").removeClass("column-left");
        } 
    }

    $(function() {
        $("#id_person-is_client_pi").change(function(){
            if($('#id_person-is_client_pi').is(':checked')){
                $(".pi-client").hide();
            }
            else{
                $(".pi-client").show();
            }
        });

        $('#id_person-lab').change(function() {
            choose_lab();
        });

        $('#id_lab-location').change(function() {
            check_lab_location()
        });
        
        $('#labAddress tbody tr').formset({
            prefix: "{{labaddform.prefix}}",
            added: function(row){
                    $('#labAddress tbody tr:last').attr("Style","display: none;");
                },
            removed: function(row){
                $('#labAddress tbody tr:last').attr("Style","display: table-row;");
            }
        })

        $("#new-client").submit(function(){
            if($('#id_person-is_client_pi').is(':checked')){
                $("#id_lab-first_name").val($("#id_person-first_name").val());
                $("#id_lab-last_name").val($("#id_person-last_name").val());
                $("#id_lab-email").val($("#id_person-email").val());
            }
        })
        choose_lab();
        $('#labAddress tbody tr:first td a').remove();
    });

</script>
{% endblock js %}

{% block messages %}
    {{ block.super }}
    {% if form.errors or labform.errors %}
        <div class='notification error png_bg'>
            <a href="#" class="close">
                <img src="{% static 'images/icons/cross_grey_small.png' %}" 
                    title="Close this notification" alt="close"></a>
            <div>Please fill out the form as indicated below.</div>
            {{ form.non_field_errors.as_ul }}
            {% if labform.non_field_errors %}
                {{ labform.non_field_errors }}
            {% endif %}
        </div>
    {% endif %}
    {% if messages %}
        <div class='notification success png_bg'>
            <a href="#" class="close">
                <img src="{% static 'images/icons/cross_grey_small.png' %}" 
                    title="Close this notification" alt="close"></a>
            {% for message in messages %}            
            <div>{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock messages %}

{% block content %}
    <h2>Add Client</h2>
    <div class="content-box">
        <div class="content-box-header">
            <h3>New Client</h3>
        </div>
        <div class="content-box-content">
        <form id="new-client" method="post" action="">{% csrf_token %}
            <div id="new-client-lab">
                <table>
                    {% load formutil %}
                    {% trfield form.first_name %}
                    {% trfield form.last_name %}
                    {% trfield form.email %}
                    <tr>
                        {% thfield form.phone %}
                        <td>
                            {{ form.extension }} {{ form.phone }}
                        </td>
                        <td class="last">
                            {% if form.errors.phone %}
                                <span class="input-notification error png_bg">
                                {{ form.phone.errors.0}}
                                </span>
                            {% endif %}
                        </td>
                    </tr>
                    {% trfield form.lab %}
                    <tr id="campus">
                        <th class="first">Campus box:</th><td></td><td class="last"></td>
                    </tr>
                    <tr id="dept">
                        <th class="first">Department Number:</th><td></td><td class="last"></td>
                    </tr>
                    {% trfield form.is_client_pi 'new-lab' %}
                    {% trfield labform.first_name 'new-lab pi-client' %}
                    {% trfield labform.last_name 'new-lab pi-client' %}
                    {% trfield labform.email 'new-lab pi-client' %}
                    {% trfield labform.location 'new-lab' %}
                    {% trfield labform.campus_box 'new-lab internal' %}
                    {% trfield labform.department 'new-lab internal' %}
                    {% trfield labform.institution 'new-lab external'%}
                    <tr><td colspan="3">
                    <table id="labAddress" class='new-lab external'>
                    {{ labaddform.management_form }}
                    {% for f in labaddform.forms %}
                        {% if forloop.first %}
                        <thead>
                            <tr>
                                {% thfield f.street %}
                                {% thfield f.city %}
                                {% thfield f.state %}
                                {% thfield f.zipcode %}
                                {% thfield f.type %}
                            </tr>
                        </thead>
                        {% endif %}
                        <tr tagName='TR'>
                            {% tdfield f.street %}
                            {% tdfield f.city %}
                            {% tdfield f.state %}
                            {% tdfield f.zipcode %}
                            {% tdfield f.type %}
                        </tr>
                    {% endfor %}
                    </table></td></tr>
                </table>
                <input class="button" type="submit" value="Add" />
            </div>
        </form>
        </div>
    </div>
    <div class="clear"></div>
{% endblock content %}

theme/templates/base/signin.html
{% extends "frontend/signin.html"}

{% block content %}
<form action="" method="post" accept-charset="utf-8">
    {{ form }}

    <input type="submit" value="Continue &rarr;"></p>
</form>
{% endblock content %}