base/urls.py
from django.conf.urls import *


urlpatterns = patterns('',
    url(r'^json/$', 'base.views.client_json', name='client-json'),
    url(r'^add/$', 'base.views.client_add', name='client-add' ),
    url(r'^browse/$', 'base.views.client_browse', name='client-browse' ),
    url(r'^client-list/$', 'base.views.client_list', name='combo-client-list'), 
    url(r'^(?P<id>\d+)/$', 'sts.views.client_detail', name='client-detail'),
    url(r'^$', 'sts.views.client_list', name='client-list'),
    )

seq/urls.py
from django.conf.urls import *


urlpatterns = patterns('',
    #url(r'^seqsamples/$', 'seq.views.sequencing_samples', name='seq-sequencing-samples' ),
    #url(r'^flowcell/create/$', 'seq.views.flowcell_create', name='flowcell-create'),
    url(r'^flowcell/samplequeue/$', 'seq.views.sequence_sample_queue', name='sample-queue'),
    url(r'^flowcell/miseqsamplequeue/$', 'seq.views.miseq_sequence_sample_queue', name='myseq-sample-queue'),
    url(r'^flowcell/seqsamplequeuejson/$', 'seq.views.seq_sample_queue_json', name='sample-queue-json'),
    url(r'^spredsheet/$', 'seq.views.miseq_spedsheet', name='miseq-spredsheet'),
    url(r'^sequencing_calculation/$', 'seq.views.sequencing_calculation', name='sequencing-calculation'),
    url(r'^run/create/$', 'seq.views.flowcell_create', name='run-create'),
    url(r'^run/edit/(?P<key>[\w-]+)/$', 'seq.views.flowcell_edit', name='run-edit'),
    url(r'^run/browse/$', 'seq.views.run_browse', name='run-browse'),
    url(r'^sequencing/contact/(?P<id>[\d-]+)/$', 'seq.views.sequencingContactActivity', name='sequencing-contact-activity'),
    url(r'^sequencing/lab/(?P<id>[\d-]+)/$', 'seq.views.sequencingLabActivity', name='sequencing-lab-activity'),
    url(r'^run/(?P<key>[\w-]+)/$', 'seq.views.run_detail', name='run-detail'),
    url(r'^flowcell/browse/$', 'seq.views.flowcell_browse', name='flowcell-browse'),
    url(r'^flowcell/(?P<key>[\w-]+)/$', 'seq.views.flowcell_detail', name='flowcell-detail' ),
)

sts/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

import menus
menus.autodiscover()

from tastypie.api import Api
#from core import api as coreapi
from billing import api as billingapi

v1_api = Api(api_name='v1')
v1_api.register(billingapi.BatchMultiplierResource())
v1_api.register(billingapi.BaseCodeResource())

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^client/', include('base.urls')),
    #url(r'^submit/$', 'sample.views.submit', name='submit' ),
    url(r'^specimen-submit/$', 'sample.views.specimen_submit', name='specimen-submit' ),
    url(r'^ngsubmit/$', 'sample.views.nextgen_submit', name='nextgen-submit' ),
    url(r'^specPegination/$', 'sample.views.getSpecimenPaginatedData', name='getSpecimenPaginatedData' ),
    url(r'^libprep/', include('libprep.urls')),
    url(r'^seq/', include('seq.urls')),
    url(r'^samp/', include('sample.urls')),
    url(r'^analysis/', include('analysis.urls')),
    url(r'^billing/', include('billing.urls')),
    url(r'^fr/', include('frontend.urls')),
    url(r'^submission/browse/$', 'sample.views.submission_browse', name='submission-browse' ),
    url(r'^run/browse/$', 'seq.views.run_browse', name='run-browse'),
    url(r'^signin/$', 'django.contrib.auth.views.login', {
        'template_name': 'frontend/signin.html',
    }),
    url(r'^signout/$', 'django.contrib.auth.views.logout', {
        'next_page': '/signin/',
    }, name="signout"),
    url(r'^favicon\.ico$', 'django.views.generic.RedirectView', {'url': '/static/img/favicon.ico'}),
    url(r'^api/', include(v1_api.urls)),
    url(r'^$', 'base.views.dashboard', name='dashboard' ),
    url(r'^seq/flowcell_json$', 'seq.views.flowcell_json', name='flowcell-json'),
    url(r'^custom_report/', include('custom_report.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

base/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from core import models as coremodels
from localflavor.us.models import USStateField

class EmailImage(models.Model):
    name = models.SlugField(help_text='')
    image = models.ImageField(upload_to='emailimages/', help_text='')
    
    def __unicode__(self):
        return u'%s' % (self.name)
    
    @models.permalink
    def get_absolute_url(self):
        return ('emailimage-view', [str(self.id)])
        
class Department(coremodels.CoreModel):
    number = models.IntegerField(db_column='DEPT_NUMBER')
    name = models.CharField(max_length=255, blank=True, null=True, help_text='')
    #slug = AutoSlugField(populate_from=('name', 'number'), overwrite=True)
    
    def __unicode__(self):
        return u'%d' % (self.number,)
    
    @models.permalink
    def get_absolute_url(self):
        return ('department-view', [str(self.id)])
        
    class Meta:
        # get_latest_by = ""
        ordering = ['name', ]
        # unique_together(('',''), )
        # verbose_name_plural = ""
        pass


class LabAddress(coremodels.CoreModel):
    ADDRESS_TYPES = (
        ('billing', 'Billing'),
        ('shipping', 'Shipping'),
        ('mailing ', 'Mailing '),
    )
    lab = models.ForeignKey("Lab", related_name='addresses')
    street = models.CharField(max_length=255, help_text='')
    city = models.CharField(max_length=255, default="St. Louis", help_text='')
    state = USStateField(default="MO", help_text='')
    zipcode = models.CharField(max_length=20, help_text='')
    type = models.CharField(max_length=255, choices=ADDRESS_TYPES, default="billing", help_text='')
    primary = models.BooleanField(default=False, help_text='')
    publish = models.BooleanField(default=True, help_text='')

    def __unicode__(self):
        return u'%s %s, %s, %s' % (self.street, self.city, self.state, self.zipcode)
        
    class Meta(coremodels.CoreModel.Meta):
        # get_latest_by = ""
        # ordering = []
        # unique_together(('',''), )
        verbose_name_plural = "Addresses"

#LabAddress._meta.get_field('type')._choices = (
#        ('billing', 'Billing'), ('mailing', 'Mailing')
#        )


class Lab(coremodels.CoreModel):
    last_name = models.CharField(max_length=255 )
    first_name = models.CharField(max_length=255, blank=True, null=True )
    shortname = AutoSlugField(populate_from=('last_name', 'first_name'), unique=True)
    location = models.CharField(max_length=10, choices=(('internal', "Internal"), ('external', 'External')))
    institution = models.CharField(max_length=255, blank=True, null=True )
    campus_box = models.PositiveIntegerField(blank=True, null=True)
    department = models.ForeignKey(Department, blank=True, null=True)
    primary_contact = models.ForeignKey("Client", blank=True, null=True, related_name="lab_primary_set")
    
    def __unicode__(self):
        if (self.first_name is None):
            return u'%s' % str(self.last_name)
        else:
            return u'%s' % str(self.first_name +' ' + self.last_name)

    @models.permalink
    def get_absolute_url(self):
        return ('lab-detail', [str(self.id)])
        
    class Meta(coremodels.CoreModel.Meta):
        # get_latest_by = ""
        ordering = ['last_name', 'first_name']
        unique_together = ('last_name', 'first_name')
        # verbose_name_plural = ""
        pass

    def save(self, *args, **kwargs):
        if self.location == 'internal':
            for x in (self.campus_box, self.department):
                if not x: 
                    raise Exception("For internal labs, you must specify a campus_box and department")
        elif self.location == 'external':
            #for x in (self.city,self.state,self.zipcode,self.street):
                #if not x:
                    #raise ValidationError("For external labs, you must specify all address information.")
            pass

        super(Lab, self).save(*args, **kwargs)


class ActiveClientManager(models.Manager):
    def get_queryset(self):
        return super(ActiveClientManager, self).get_query_set().filter(person__user__is_active=True)

class Client(coremodels.PersonType):
    lab = models.ForeignKey(Lab, blank=True, null=True, help_text='')

    objects = models.Manager()
    active = ActiveClientManager()
        
    @models.permalink
    def get_absolute_url(self):
        return ('client-detail', [str(self.id)])

    def __unicode__(self):
        return u'%s [%s]' % (self.name, self.lab)
 
    class Meta(coremodels.PersonType.Meta):
        pass

class Employee(coremodels.PersonType):

    @models.permalink
    def get_absolute_url(self):
        return ('employee-detail', [str(self.id)])
    

theme/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.forms.models import modelform_factory
from base import models as basemodels 
from core import models as coremodels 
from django.contrib.admin.widgets import AdminFileWidget
from django.contrib.auth.models import User
import localflavor.us.forms as usforms 
from django.core import validators


class Simple(forms.Form):
    email = forms.EmailField(label="Your email address")


class ClientAddForm(forms.ModelForm):
    first_name = forms.CharField(label='First Name', error_messages={
                    "required": "Please enter the first name",
                })
    last_name = forms.CharField(label='Last Name', error_messages={
                    "required": "Please enter the last name",
                })
    email = forms.EmailField(error_messages={
                    "required": "Please enter the email address",
                })
    phone = usforms.USPhoneNumberField(error_messages={
                    "required": "Please enter the phone number",
                    "invalid": "Phone numbers must be in (CCC) XXX-XXX-XXXX format.",
                },
                help_text="(CCC) XXX-XXX-XXXX", widget=forms.TextInput(attrs={'maxlength': '10', 'size': '13'}))
    extension = forms.IntegerField(label="Country Code", required=False, initial="1", widget=forms.TextInput(attrs={'maxlength': '3', 'size': '3'}))
    lab = forms.ModelChoiceField(basemodels.Lab.objects.all(), empty_label="New Lab", required=False)

    is_client_pi = forms.BooleanField(label="Is Client PI?", required=False)

    class Meta:
        model = coremodels.Person
        exclude = ('email', 'gender', 'user')

    def clean(self):
	cd = self.cleaned_data
	if 'phone' in cd and cd['phone'] and not cd['extension']:
	    self._errors["phone"] = self.error_class(['Phone numbers must be in (CCC) XXX-XXX-XXXX format.'])
	return cd
	

class LabAddForm(forms.ModelForm):
    department = forms.IntegerField(label="Department Number", required=False)
    last_name = forms.CharField(label='PI Last Name',
                error_messages={"required": "Please enter the PI last name ",},
                help_text="""
For labs headed by a PI: "FIRSTNAME LASTNAME Lab"

For other "labs" (centers, businesses): use the official name.
    """)
    first_name = forms.CharField(label='PI First Name', required=False)
    email = forms.EmailField(label="PI Email", error_messages={
                    "required": "Please enter the email address",
                })
    location = forms.ChoiceField(choices=(('','---------'),('internal', "Internal"), ('external', 'External')),
                        error_messages={"required": "Please select the lab's location.",},)
    
    class Meta:
        model = basemodels.Lab
        exclude = ('primary_contact', 'department')

    def save(self, *args, **kwargs):
        lab = super(LabAddForm, self).save(*args, commit=False, **kwargs)
        if self.cleaned_data['location'] == 'internal':
            lab.department = basemodels.Department.objects.get_or_create(number=self.cleaned_data['department'])[0]
        lab.save()
        return lab

    def clean(self):
        cd = self.cleaned_data
        if 'last_name' in cd and (basemodels.Lab.objects.filter(last_name=cd['last_name'], first_name=cd['first_name']).count() > 0):
            raise forms.ValidationError("PI Name is already in use'")
         
        if 'location' in cd and cd['location'] == 'internal':
            for x in ('department', 'campus_box'):
                if x in cd and not cd[x]:
                    self._errors[x] = self.error_class(['Internal labs must specify a %s.' % x,])
        if 'location' in cd and cd['location'] == 'external':
            if 'institution' in cd and not cd['institution']:
                self._errors['institution'] = self.error_class(['External labs must specify the institution.'])
        return cd

class BaseLabAddressFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        super(BaseLabAddressFormSet, self).__init__(*args, **kwargs)
        self.forms[0].empty_permitted = False

LabAddressFormset = inlineformset_factory(basemodels.Lab, basemodels.LabAddress, extra=1, max_num=2, formset=BaseLabAddressFormSet, fields='__all__')

theme/views.py
# Create your views here.

theme/templates/gtac/analysis-tracking.html
{% extends "gtac/base.html" %}

{% block content %}

<table>
    <tr>
    <th>Run ID</th>
    <th>Seq ID</th>
    <th>Lab</th>
    <th>Species</th>
    <th>Seq. Start</th>
    <th>Indexes</th>
    </tr>

    {% for lane in lanes %}
    <tr>
    <td><a href="{{ lane.get_absolute_url }}">{{ lane.flowcell.run.num }}_{{ lane.number }}</a></td>
    <td><a href="{{ lane.denaturedaliquot.sequencingsample.get_absolute_url }}">{{ lane.denaturedaliquot.sequencingsample.name }}</a></td>
    <td>

    {% regroup lane.denaturedaliquot.sequencingsample.samplesubmissions by submission.client.lab as bylab %}
    
    {% for lab in bylab %}
    <a href="{{ lab.grouper.get_absolute_url }}">{{ lab.grouper }}</a>
    
    {% comment %}
    {% for item in lab.list %} <a href="{{ item.sample.get_absolute_url }}">{{ item.sample.name }}</a>{% if not forloop.last %}, {% endif %} {% endfor %}
    {% endcomment %}
    
    {% endfor %}

    </td>
    {% with lane.denaturedaliquot.sequencingsample.samplesubmissions.0 as ss %}
    <td>{{ ss.sample.organism }}</td>
    {% endwith %}
    <td>{{ lane.flowcell.run.sequencing_date }}</td>
    <td>{% for detail in  lane.denaturedaliquot.sequencingsample.sequencingsampledetail_set.all %}{{ detail.index.name }}(<a href="{{ detail.sampleprepdetail.samplesubmission.sample.get_absolute_url }}">{{ detail.sampleprepdetail.samplesubmission.sample.name }})</a> {% endfor %} </td>
    </tr>
    {% endfor %}

</table>

{% endblock content %}

theme/templates/gtac/client-box.html
<h2>{{ client.name }}</h2>
<p>Lab: <a href="{{ client.lab.get_absolute_url }}">{{ client.lab.name }}</a></p>
{% for email in client.person.email_addresses.all %}
<p>{{ email.get_type_display|slice:':1' }}: <a href="mailto:{{ email.email }}">{{ email.email }}</a></p>
{% endfor %}
{% for phone in client.person.phone_numbers.all %}
<p>{{ phone.get_type_display|slice:':1' }}: {{ phone.number }}</p>
{% endfor %}

<h2>Latest Submissions</h2>
{% for sub in client.submission_set.all|slice:":5" %}
<p><a href="{{ sub.get_absolute_url }}">{{ sub.submitted }}</a></p>
{% endfor %}

theme/templates/gtac/client-detail.html
{% extends "gtac/base.html" %}

{% block content %}
<div id="client-detail">
<h2>{{ client.name }}</h2>
<h3>{{ client.lab }} Lab</h3>

<h3>{{ client.submission_set.count }} Submission{{ client.submission_set.count|pluralize }}</h3>
<ul>
{% for sub in client.submission_set.all %}
<li><a href="{{ sub.get_absolute_url }}">{{ sub }}</a></li>
{% endfor %}
</ul>
</div>
{% endblock content %}

{% block links %}
<div class="box">{% include "gtac/client-box.html" %}</div>
{% endblock links %}

theme/templates/gtac/flowcell-detail.html
{% extends "gtac/base.html" %}

{% block content %}
<div id="flowcell-detail">
{%load static from staticfiles %}
<img id="flowcell-photo" src="{% static '/static/img/flowcell.gif' %}"/>
<h2>Flowcell: {{ fc.name }}</h2>



<h3>Lanes</h3>
<table>
<thead>
<tr>
<th>#</th>
<th>Samples</th>
<th>PhiX Spike</th>
<th>Loading Concentration</th>
</tr>
</thead>
<tbody>
{% for l in fc.lanes.all %}
<tr>
<td><a href="{{ l.get_absolute_url }}">{{ l.number }}</a></td>
<td>{% for ss in l.samplesubmissions %}<a href="{{ ss.get_absolute_url }}">{{ ss.sample.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</td>
<td>{{ l.denaturedaliquot.phix_spike }}</td>
<td>{{ l.denaturedaliquot.loading_concentration }}</td>
</tr>
{% endfor %}
        
</table>

</div>
{% endblock content %}

{% block links %}
<div class="box">{% include "gtac/flowcell-box.html" %}</div>
{% if fc.run %}
<div class="box">{% with fc.run as run %}{% include "gtac/run-box.html" %}{% endwith %}</div>
{% endif %}
{% endblock links %}

theme/templates/gtac/home.html
{% extends "gtac/base.html" %}

{% block content %}
<h2>Content</h2>

<form action="test" method="get">
    <input id="test" type="text"> <label for="test">Test</label>

    <p><input type="submit" value="Continue &rarr;" /></p>
</form>
{% endblock content %}

theme/templates/gtac/lab-detail.html
{% extends "gtac/base.html" %}

{% block content %}
<div id="lab-detail">
<h2>{{ lab.name }} Lab</h2>
</div>
{% endblock content %}

{% block links %}

{% endblock links %}

theme/templates/gtac/lane-box.html
<h2>Lane {{ lane.number }}</h2>

theme/templates/gtac/lane-detail.html
{% extends "gtac/base.html" %}

{% block extrahead %}
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
    
      // Load the Visualization API and the piechart package.
      google.load('visualization', '1', {'packages':['corechart']});
      
      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);
      
      // Callback that creates and populates a data table, 
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {

      // Create our data table.
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Sample');
      data.addColumn('number', 'percent');
      data.addRows([
        {% for ssd in lane.denaturedaliquot.sequencingsample.sequencingsampledetail_set.all %}
        {% with ssd.sampleprepdetail.samplesubmission as sub %}
        ['{{ sub.sample.name }}', {{ ssd.percent_of_pool }}]{% if not forloop.last %},{% endif %}
        {% endwith %}
        {% endfor %}
      ]);

      // Instantiate and draw our chart, passing in some options.
      var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
      chart.draw(data); //, {width: 400, height: 240});
    }
    </script>
{% endblock extrahead %}


{% block content %}
<div id="lane-detail">
<h2>Run <a href="{{ lane.flowcell.run.get_absolute_url }}">{{ lane.flowcell.run }}</a> Lane {{ lane.number }}</h2>



<h3>Lane Analysis Statistics</h3>
{% for pps in lane.postprocess_set.all.distinct %}
<div class="stats">
<table>
<thead>
<tr><th colspan="2">{{ pps.run_post_process.date }}</th></tr>
</thead>
<tbody>
{% for v in pps.postprocessvalue_set.all.distinct %}
<tr><th>{{ v }}</th><td>{{ v.value }}</td></tr>
{% endfor %}
</table>
</div>

{% endfor %}

</div>
{% endblock content %}

{% block links %}
<div class="box">{% include "gtac/lane-box.html" %}</div>
<div class="box">{% with lane.flowcell.run as run %}{% include "gtac/run-box.html" %}{% endwith %}</div>

<div class="box">
<h2>Lane {{ lane.number }} Samples</h2>
{% for ssd in lane.denaturedaliquot.sequencingsample.sequencingsampledetail_set.all %}
{% with ssd.sampleprepdetail.samplesubmission as sub %}
<p><a href="{{ sub.submission.get_absolute_url }}">{{ sub.sample.name }} ({{ ssd.percent_of_pool }}%) </a> - <a href="{{ sub.submission.client.get_absolute_url }}">{{ sub.submission.client.first_name }} {{ sub.submission.client.last_name }}</a></p>
{% endwith %}
{% endfor %}
</div>
<div style="width: 100%; height: 200px;" id="chart_div"></div>
{% endblock links %}

theme/templates/gtac/run-detail.html
{% extends "gtac/base.html" %}

{% block content %}
<div id="run-detail">

{% if run.manifold.sequencer.model.image %}<img id="sequencer-photo" src="{{ run.manifold.sequencer.model.image.url }}" />{% endif %}
<h2>Run: {{ run.num }} - {{ run.status }}{% if run.failed %}FAILED{% endif %}</h2>

<h3>Lanes</h3>
<table>
<thead>
<tr>
<th>#</th>
<th>Samples</th>
<th>DNA Concentration</th>
</tr>
</thead>
<tbody>
{% for l in run.flowcell.lanes.all %}
<tr>
<td><a href="{{ l.get_absolute_url }}">{{ l.number }}</a></td>
<td>{% for ss in l.samplesubmissions %}<a href="{{ ss.sample.get_absolute_url }}">{{ ss.sample.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</td>
<td>{{ l.submitted_conc }}</td>
</tr>
{% endfor %}
</table>



<h2>Analysis Results</h2>
{% for rpp in run.runpostprocess_set.all %}
<h3>{{ rpp.date }}</h3>
<p>Results File: <a href="{{ rpp.results_file.url }}">download</a></p>
<p>Control Lane: <a href="{{ rpp.control_lane.get_absolute_url }}">{{ rpp.control_lane.flowcell.run }}-{{ rpp.control_lane.number }}</a></p>
{% endfor %}

</div>
   
{% endblock content %}


{% block links %}
<div class="box">{% include "gtac/run-box.html" %}</div>
{% endblock links %}

theme/templates/gtac/sample-box.html
<h2><a href="{{ sample.get_absolute_url }}">{{ sample.name }}</a></h2>
<p>Initial Submit: <a href="{{ sample.submitted_from.get_absolute_url }}">{{ sample.submitted_from.submitted }}</a></p>
<p>Submitter: <a href="{{ sample.submitted_from.client.get_absolute_url }}">{{ sample.submitted_from.client }}</a></p>
<p>Organism: {{ sample.organism.name }}</p>

theme/templates/gtac/sample-detail.html
{% extends "gtac/base.html" %}

{% block content %}
<div id="sample-detail">
<h2>Sample: {{ sample.name }}</h2>
{% if sample.organism.image %}<div id="organism-photo"><img src="{{ sample.organism.image.url }}" /><p>{{ sample.organism.name }}</p></div>{% endif %}
<div id="notes">
{% load markup %}
<h2>Notes</h2>
{{ sample.notes|markdown }}
</div>

</div>
{% endblock content %}

{% block links %}
<div class="box">{% include "gtac/sample-box.html" %}</div>

{% if sample.submissions %}
<div class="box">
<h2>Used in {{ sample.submissions.count }} Submission{{ sample.submissions.count|pluralize }}</h2>
{% for sub in sample.submissions.all %}
<p><a href="{{ sub.get_absolute_url }}">{{ sub.submitted }}</a></p>
{% endfor %}
</div>
{% endif %}

{% endblock links %}

theme/templates/gtac/submission-box.html
<h2><a href="{{ sample.get_absolute_url }}">{{ sample.name }}</a></h2>
<p>Initial Submit: {{ sample.submitted_from.submitted }}</p>
<p>Submitter: <a href="{{ sample.submitted_from.client.get_absolute_url }}">{{ sample.submitted_from.client }}</a></p>
<p>Organism: {{ sample.organism.name }}</p>
<p></p>

theme/templates/gtac/submission-detail.html
{% extends "gtac/base.html" %}

{% block content %}
<div id="submission-detail">
<h2>Submission: {{ submission.submitted }}</h2>
<p>Submitted by: <a href="{{ submission.client.get_absolute_url }}">{{ submission.client }}</a></p>

<h3>Samples</h3>
<table>
<thead>
<tr><th>Sample</th><th>Submitted to Sequencing</th><th>Runs</th></tr>
</thead>
{% for ss in submission.samplesubmission_set.all %}
<tr>
<th><a href="{{ ss.sample.get_absolute_url }}">{{ ss.sample }}</a></th>
<td>{% for ssd in ss.sequencingsampledetail_set.all %}
<a href="{{ ssd.sequencingsample.get_absolute_url }}">{{ ssd.sequencingsample }}</a> ({{ ssd.percent_of_pool }}%)
{% endfor %}
</td>
<td>{% for runs in ss.seq.runs %} {{ run }} {% endfor %}</td>

</tr>




{% endfor %}


</table>
</div>
{% endblock content %}

{% block links %}
{% for ss in submission.samplesubmission_set.all %}
<div class="box">
<h2>{{ ss.sample.name }}</h2>
{% for sequencingsample in ss.sequencingsample_set.all %}
<p><a href="{{ sequencingsample.get_absolute_url }}">{{ sequencingsample.name }}</a></p>
{% endfor %}
</div>
{% endfor %}
{% endblock links %}

theme/templates/gtac/turnaround.html
{% extends "gtac/base.html" %}

{% block extrahead %}
<script type="text/javascript" charset="utf-8">
// <![CDATA[
    $(function() {
        $('table').flexigrid();
        });
// ]]>
</script>
<style type="text/css" media="screen">
/* <![CDATA[ */
#links {
display: none;
}
#turnaround {
width: 100%;
margin: 0;
}
#page {
width: 100%;
}
/* ]]> */
</style>

{% endblock extrahead %}

{% block contentid %}turnaround{% endblock contentid %}
{% block content %}
<table>
<thead>
<tr>
</tr>
</thead>
<tbody>
{% for ss in samplesubmissions %}
<tr>
<td>{{ ss.id }}</td>
<td>{% for seqs in ss.libprep.sequencingsamples.all %}<a href="{{ seqs.get_absolute_url }}">{{ seqs.name }}</a>{% if not forloop.first %},{% endif %}{% endfor %}</td>
<td>{% for da in ss.seq.denaturedaliquot.all %}<a href="{{ da.lane.flowcell.run.get_absolute_url }}">{{ da.lane.flowcell.run }}</a>:<a href="{{ da.lane.get_absolute_url }}">{{ da.lane.number }}</a>{% endfor %}</td>
<td><a href="{{ ss.submission.client.lab.get_absolute_url }}">{{ ss.submission.client.lab }}</a></td>
<td>{{ ss.libprep.preptype }}</td>
<td>{{ ss.seq.runtype }}</td>


<td>{{ ss.submission.submitted }}</td>
<td>{{ ss.libprep.complete_date }}</td>
<td>{{ ss.seq.ready_date }}</td>
<td>{{ ss.seq }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock content %}