libprep/urls.py
from django.conf.urls import *
from libprep import views

urlpatterns = patterns('',

    url(r'^projects/$', 'libprep.views.projects', name='libprep-projects'),
    url(r'^myprojects/$', 'libprep.views.my_projects', name='libprep-my-projects'),
    url(r'^projects/add/$', views.NewProjectView.as_view(), name='libprep-project-add'),
    url(r'^projects/(?P<id>\d+)/$', 'libprep.views.project_detail', name='libprep-project-detail'),
    url(r'^projectMockupSheet/(?P<id>\d+)/$', 'libprep.views.projectMockupSheet', name='libprep-project-MockupSheet'),
    url(r'^addsampletoproject/(?P<id>\d+)/$', 'libprep.views.add_samples_to_project', name='libprep-add-sample-to-project'),
    url(r'^new-submissions/$', 'libprep.views.new_submissions', name='new-submissions'),
    url(r'^new-submissions/$', 'libprep.views.new_submissions', name='new-submissions'),
    url(r'^sample/browse/$', 'libprep.views.sample_browse', name='libprep-sample-browse' ),
    url(r'^submission/assign/$', 'libprep.views.submission_assign', name='libprep-submission-assign'),
    url(r'^myqueue/$', 'libprep.views.my_queue', name='libprep-my-queue'),
    url(r'^prepsequencing/$', 'libprep.views.prep_for_sequencing', name='libprep-prep-sequencing' ),
    url(r'^seqsamples/(?P<key>[\w-]+)/$', 'libprep.views.seqsample_detail', name='libprep-seqsample-detail'),
    url(r'^seqsamples/$', 'libprep.views.sequencing_samples', name='libprep-sequencing-samples' ),
    url(r'^directseqsamples/$', 'libprep.views.direct_to_sequencing_samples', name='libprep-direct-sequencing-samples' ),
    #url(r'^samples/$', 'libprep.views.samples', name='libprep-samples'),
    url(r'^prepSampleBrowseData/$', 'libprep.views.prep_sample_browse_data', name='libprep-prep-sample-browse-data'),
    url(r'^cancelDirectToSeqSample/(?P<id>\d+)/$', 'libprep.views.cancel_direct_to_seq_sample', name='libprep-cancel-direct-seq-sample'),
    url(r'^cancelLibCoreSeqSample/(?P<id>\d+)/$', 'libprep.views.cancel_libcore_seq_sample', name='libprep-cancel-libcore-seq-sample'),
    url(r'^deletePrepdataFile/(?P<id>\d+)/$', 'libprep.views.delete_prepdata_file', name='libprep-delete-prepdata-file'),
    url(r'^seqsampleAllDetails/(?P<key>[\w-]+)/$', 'libprep.views.seqsample_all_details', name='libprep-seqsample-all-details'),
    url(r'^reSequenceSamples/$', 'libprep.views.resequence_sample', name='libprep-prep-resequence'),
    )

sample/urls.py
from django.conf.urls import *

urlpatterns = patterns('',
    url(r'^note/$', 'sample.views.submission_note', name='submission-note' ),
    url(r'^browse/$', 'sample.views.submission_browse', name='submission-browse' ),
    url(r'^sub/(?P<id>\d+)/$', 'sample.views.submission_detail', name='submission-detail'),
    url(r'^sub/(?P<id>\d+)/notes/$', 'sample.views.submission_note_list', name='submission-note-list' ),
    url(r'^sample_json/$', 'sample.views.sample_json', name='sample-json'),
    url(r'^submission_json/$', 'sample.views.submission_json', name='submission-json'),
    url(r'^samplesubmission_json/$', 'sample.views.samplesubmission_json', name='samplesubmission-json'),
    url(r'^96well_submission.csv$', 'sample.views.submission96_csv', name='submission-96-csv' ),
    url(r'^sample/browse/$', 'sample.views.sample_browse', name='sample-browse'),
    url(r'^sample/(?P<id>\d+)/$','sample.views.sample_details', name='sample-details'),
    url(r'^submission_report/$','sample.views.submission_report', name='submission-report'),
    url(r'^client/(?P<id>\d+)/$','sample.views.getICTS_research_data', name='sample-ICTS-reserch-data'),
    )

seq/urls.py
from django.conf.urls import *


urlpatterns = patterns('',
    #url(r'^seqsamples/$', 'seq.views.sequencing_samples', name='seq-sequencing-samples' ),
    #url(r'^flowcell/create/$', 'seq.views.flowcell_create', name='flowcell-create'),
    url(r'^flowcell/samplequeue/$', 'seq.views.sequence_sample_queue', name='sample-queue'),
    url(r'^flowcell/miseqsamplequeue/$', 'seq.views.miseq_sequence_sample_queue', name='myseq-sample-queue'),
    url(r'^flowcell/seqsamplequeuejson/$', 'seq.views.seq_sample_queue_json', name='sample-queue-json'),
    url(r'^spredsheet/$', 'seq.views.miseq_spedsheet', name='miseq-spredsheet'),
    url(r'^sequencing_calculation/$', 'seq.views.sequencing_calculation', name='sequencing-calculation'),
    url(r'^run/create/$', 'seq.views.flowcell_create', name='run-create'),
    url(r'^run/edit/(?P<key>[\w-]+)/$', 'seq.views.flowcell_edit', name='run-edit'),
    url(r'^run/browse/$', 'seq.views.run_browse', name='run-browse'),
    url(r'^sequencing/contact/(?P<id>[\d-]+)/$', 'seq.views.sequencingContactActivity', name='sequencing-contact-activity'),
    url(r'^sequencing/lab/(?P<id>[\d-]+)/$', 'seq.views.sequencingLabActivity', name='sequencing-lab-activity'),
    url(r'^run/(?P<key>[\w-]+)/$', 'seq.views.run_detail', name='run-detail'),
    url(r'^flowcell/browse/$', 'seq.views.flowcell_browse', name='flowcell-browse'),
    url(r'^flowcell/(?P<key>[\w-]+)/$', 'seq.views.flowcell_detail', name='flowcell-detail' ),
)

sts/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

import menus
menus.autodiscover()

from tastypie.api import Api
#from core import api as coreapi
from billing import api as billingapi

v1_api = Api(api_name='v1')
v1_api.register(billingapi.BatchMultiplierResource())
v1_api.register(billingapi.BaseCodeResource())

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^client/', include('base.urls')),
    #url(r'^submit/$', 'sample.views.submit', name='submit' ),
    url(r'^specimen-submit/$', 'sample.views.specimen_submit', name='specimen-submit' ),
    url(r'^ngsubmit/$', 'sample.views.nextgen_submit', name='nextgen-submit' ),
    url(r'^specPegination/$', 'sample.views.getSpecimenPaginatedData', name='getSpecimenPaginatedData' ),
    url(r'^libprep/', include('libprep.urls')),
    url(r'^seq/', include('seq.urls')),
    url(r'^samp/', include('sample.urls')),
    url(r'^analysis/', include('analysis.urls')),
    url(r'^billing/', include('billing.urls')),
    url(r'^fr/', include('frontend.urls')),
    url(r'^submission/browse/$', 'sample.views.submission_browse', name='submission-browse' ),
    url(r'^run/browse/$', 'seq.views.run_browse', name='run-browse'),
    url(r'^signin/$', 'django.contrib.auth.views.login', {
        'template_name': 'frontend/signin.html',
    }),
    url(r'^signout/$', 'django.contrib.auth.views.logout', {
        'next_page': '/signin/',
    }, name="signout"),
    url(r'^favicon\.ico$', 'django.views.generic.RedirectView', {'url': '/static/img/favicon.ico'}),
    url(r'^api/', include(v1_api.urls)),
    url(r'^$', 'base.views.dashboard', name='dashboard' ),
    url(r'^seq/flowcell_json$', 'seq.views.flowcell_json', name='flowcell-json'),
    url(r'^custom_report/', include('custom_report.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

theme/models.py
from django.db import models

# Create your models here.

libprep/forms.py
from django import forms
from libprep import models as lpmodels
from sample import models as sampmodels
from django.forms.models import modelformset_factory, inlineformset_factory
from django.forms.formsets import formset_factory
from base import models as basemodels
from django.utils.safestring import mark_safe
from django.utils.datastructures import SortedDict
from operator import itemgetter, attrgetter
import re
import logging

logger = logging.getLogger('myproject.custom')

class NewProject(forms.Form):
    prep_type = forms.ModelChoiceField(lpmodels.PrepType.active.filter(sampleprepdetail__complete=False, 
                       preptypeversion__is_active=True, preptypeversion__isnull=False).defer('submission_guidelines').distinct())
    samples = forms.ModelMultipleChoiceField(queryset=lpmodels.SamplePrepDetail.objects.filter(complete=False, projects=None))


class AddSampleToProject(forms.Form):
    samples = forms.ModelMultipleChoiceField(queryset=lpmodels.SamplePrepDetail.objects.none())
    
    def __init__(self, *args, **kwargs):
        queryset = kwargs.pop('queryset')
        super(AddSampleToProject, self).__init__(*args, **kwargs)
        self.fields['samples'].queryset = queryset


PROJECT_STATUS = (
    ('qc','QC'),
    ('qc complete','QC Complete'),
    ('hold','Hold'),
    ('prepping','Prepping'),
    ('failed', 'Failed'),
    ('prep completed','Prep Completed'),
    )

class ChangeProjectStatus(forms.Form):
    qc_owner = forms.ModelChoiceField(basemodels.Employee.objects.all(), label="QC Owner", required=False)
    prep_owner = forms.ModelChoiceField(basemodels.Employee.objects.all(), label="Prep Owner", required=False)
    status = forms.ChoiceField(choices=PROJECT_STATUS, required=True)

    def clean(self):
        cd = self.cleaned_data
        if 'status' in cd and cd['status']:
            if cd['status'] == 'qc' and not cd['qc_owner']:
                self._errors["qc_owner"] = self.error_class(['This field is required'])
            elif cd['status'] == 'prepping' and not cd['prep_owner']:
                self._errors["prep_owner"] = self.error_class(['This field is required'])
        return cd


class AddProjectNote(forms.Form):
     note = forms.CharField(widget=forms.Textarea(attrs={'cols': 40, 'rows': 9}), required=True)


class NewSubmissionsForm(forms.ModelForm):
    assigned = forms.BooleanField(required=False)

    class Meta:
        model = sampmodels.Submission
        fields = ['id',]

NewSubmissionsFormset = modelformset_factory(sampmodels.Submission, form=NewSubmissionsForm, extra=0)


class NewSeqSampleForm(forms.Form):
    samples = forms.ModelMultipleChoiceField(lpmodels.SamplePrepDetail.objects.all().filter(preptype__isnull=False))


class SequencingSampleForm(forms.ModelForm):
    lanes_per_sample = forms.IntegerField(label="Number of Lanes per Sample",  initial=1, min_value=0, required=False)
    phix_spike_per_sample = forms.IntegerField(label="PhiX Spike-in per Sample",  initial=1, min_value=0, required=False)
    send_mail = forms.BooleanField(label="Do you want to send email?", required=False)

    class Meta:
        model = lpmodels.SequencingSample
        exclude = ('sampleprepdetails', 'prepped', 'barcoded', 'indexed', 'client_prepped', 'multiplex_type')

    def clean(self):
        cd = self.cleaned_data
        if not cd['lanes_per_sample']:
            self._errors["lanes_per_sample"] = self.error_class(['This field is required.']) 
        return cd

SequencingSampleFormset = inlineformset_factory(lpmodels.SequencingSample, lpmodels.SequencingSampleDetail, extra=0, can_delete=True, fields='__all__')


class SequencingSampleDetailForm(forms.Form):
    index = forms.ModelMultipleChoiceField(queryset=lpmodels.Index.objects.all(), widget=forms.SelectMultiple(attrs={'class': 'chosen-select'}), 
                                           required=False)
    sampleprepdetail = forms.ModelChoiceField(lpmodels.SamplePrepDetail.objects.all())
    percent_of_pool = forms.CharField(label="% Pool", required=False)
    areSamplesPrepared = forms.BooleanField(required=False)

    def clean(self):
        cd = self.cleaned_data
        if not cd['areSamplesPrepared'] and not cd['index']:
            self._errors['index'] = self.error_class(['This field is required.'])

        return cd
    
SequencingSampleDetailFormset = formset_factory(SequencingSampleDetailForm, extra=0)


class PreppedSampleForm(forms.ModelForm):
    class Meta:
        model = lpmodels.SequencingSample
        exclude = ('sampleprepdetails',)

# class SelectedSampleForm(forms.Form):
    # sample = forms.ModelChoiceField(lpmodels.SamplePrepDetail.objects.all()) #, widget=forms.HiddenInput)
    ##sample_name = forms.CharField(widget=forms.HiddenInput)
    ##client_name = forms.CharField(widget=forms.HiddenInput)
    # idx = forms.ModelChoiceField(lpmodels.Index.objects.all(), label="Index", )
    # percent = forms.CharField()

# SelectedSampleFormSet = formset_factory(SelectedSampleForm, extra=3)


MULTIPLEX_CHOICES = (
    ('index', "Index"),
    ('dual index', "Dual Index"),
    ('barcoded', "Barcode"),
    )

class SamplePrepDetailIndexForm(forms.Form):
    id = forms.CharField()
    index = forms.CharField()
    multiplex_type = forms.ChoiceField(choices=MULTIPLEX_CHOICES)

SamplePrepDetailIndexFormset = formset_factory(form=SamplePrepDetailIndexForm, extra=0)


#class BasePrepStepFormSet(forms.formsets.BaseFormSet):
#    def __init__(self, prepstep, project, *args, **kwargs):
#        self.prepstep = prepstep
#        self.project = project
#        #kwargs['initial'] = kwargs.get('initial', self.initial_data())
#        self.initial = kwargs.pop('initial', self.initial_data())
#        super(BasePrepStepFormSet, self).__init__(*args, **kwargs)


def prepstep_initial_global_data(prepstep, project, per_sample=True):
    data = []
    prepdata = lpmodels.PrepData.objects.filter(project=project, prepdatadef__prepstep=prepstep,
                                                prepdatadef__per_sample=per_sample).order_by('attempt')
    if not per_sample:
        prepdata = prepdata.exclude(prepdatadef__type='FILE')

    idata = {}
    for pd in prepdata:
        if per_sample:
            info = pd.prepdatadef.id, pd.sampleprepdetail.id
            key = 'pdd%d-%d' % info
        else:
            key = 'pdd%d' % pd.prepdatadef.id
        if not idata.has_key(pd.attempt):
           idata[pd.attempt] = {'attempt': pd.attempt}
        if pd.prepdatadef.type == 'FILE':
            idata[pd.attempt][key] = pd.file
        elif pd.prepdatadef.type == 'IMAGE':
            idata[pd.attempt][key] = pd.image
        else:
            idata[pd.attempt][key] = pd.value

    for i in idata:
        data.append(idata[i])

    if(len(data) == 0):
        data = [{'attempt': '1'}]

    if not per_sample:
       return data[0]
    return data

#def prepstep_initial_data(prepstep, project, per_sample=True):
#    prepdata = lpmodels.PrepData.objects.filter(project=project, prepdatadef__prepstep=prepstep, prepdatadef__per_sample=per_sample)
#
#    if per_sample:
#        idata = []
#        for spd in project.sampleprepdetail.all():
#            d = {'sampleprepdetail': spd, 'sample': spd.name }
#            for pd in prepdata:
#                if spd == pd.sampleprepdetail:
#                    if pd.prepdatadef.type == 'FILE':
#                        d['pdd%d' % pd.prepdatadef.id] = pd.file
#                    elif pd.prepdatadef.type == 'IMAGE':
#                        d['pdd%d' % pd.prepdatadef.id] = pd.image
#                    else:
#                        d['pdd%d' % pd.prepdatadef.id] = pd.value
#            idata.append(d)
#    else:
#        idata = {}
#        spd = project.sampleprepdetail.all()[0]
#        for pd in prepdata:
#            if spd == pd.sampleprepdetail:
#                if pd.prepdatadef.type == 'FILE':
#                    idata['pdd%d' % pd.prepdatadef.id] = pd.file
#                elif pd.prepdatadef.type == 'IMAGE':
#                    idata['pdd%d' % pd.prepdatadef.id] = pd.image
#                else:
#                    idata['pdd%d' % pd.prepdatadef.id] = pd.value
#            
#    return idata
#
#class BasePrepStepForm(forms.BaseForm):
#    def __init__(self, sampleprepdetail, *args, **kwargs):
#        self.sampleprepdetail = sampleprepdetail
#        super(BasePrepStepForm, self).__init__(*args, **kwargs)
#
#class ReadOnlyInput(forms.HiddenInput):
#    def render(self, name, value, **kwargs):
#        return super(ReadOnlyInput, self).render(name, value, **kwargs) + mark_safe(value)
#
#def make_prep_step_form(prepstep): 
#    fields = SortedDict()
#    fields['sampleprepdetail'] = forms.ModelChoiceField(lpmodels.SamplePrepDetail.objects.all(), widget=forms.HiddenInput)
#    fields['sample'] = forms.CharField(widget=ReadOnlyInput, required=False)
#    for pdd in prepstep.prepdatadef_set.filter(per_sample=True):
#        fields['pdd%d' % pdd.id] = get_field(pdd)
#        #FIXME: add this: #fields[pdd.slug].help_text = pdd.description
#
#    return type('PrepStepForm', (forms.BaseForm,), { 'base_fields': fields })

def get_field(pdd, instance=None):
    field = None

    # Django 1.6 switched to new default widgets for numeric fields.
    # Library Core personnel *hate* them (the spinners specifically).
    if pdd.type == 'FLOAT':
        field = forms.FloatField(widget=forms.TextInput)
    elif pdd.type == 'INT':
        field = forms.IntegerField(widget=forms.TextInput)
    elif pdd.type == 'IMAGE':
        field = forms.ImageField()
    elif pdd.type == 'FILE':
        field = forms.FileField(widget=forms.FileInput(attrs={'multiple': 'multiple'}))
    elif pdd.type == 'STR':
        field = forms.CharField()
    elif pdd.type == 'DATE':
        field = forms.DateField()
    elif pdd.type == 'TIME':
        field = forms.TimeField()
    elif pdd.type == 'BOOL':
        field = forms.BooleanField()

    if instance:
        field.initial = instance.value

theme/views.py
# Create your views here.

theme/templates/libprep/my-queue.html
{% extends "frontend/base.html" %}

{% block js %}
<script type="text/javascript">
$(function() {
  $('#sample tbody tr').formset();
  $('table').dataTable({
  });
});
</script>
{% endblock js %}

{% block content %}
<h1>Queue for {{ request.user.person.name }}</h1>
<table>
<thead>
<tr>
<th>Submission ID</th>
<th>Sample Name</th>
<th>Prep Type</th>
<th>Submitted</th>
</tr>
</thead>
<tbody>
{% for spd in sampleprepdetails %}
{% with spd.samplesubmission as ss %}
<tr>
<td><a href="{% url submission-detail ss.submission.id %}">{{ ss.submission.id }}</a></td>
<td><span data-sampkey="{{ ss.key }}">{{ spd.samplesubmission.sample.name }}</span></td>
<td>{{ spd.preptype.name }}</td>
<td>{{ spd.samplesubmission.submission.submitted }}</td>
</tr>
{% endwith %}
{% endfor %}
</tbody>
<tfoot></tfoot>
</table>
{% endblock content %}

theme/templates/libprep/project-add.html
{% extends "sts/base.html" %}
{% load static from staticfiles %}
{% block css %}
<style>
    table tr.highlight td, 
    table tr.highlight td.sorting_1 {
        background-color: {{ datatable_select_color }};
    }
    tr {
        cursor: pointer;
    }
    #id_samples {
        display: none;
    }
    
    .dataTables_wrapper {
        margin-bottom: 10px;
    }

    #main-content ul,ol {
        padding: 10px 0;
    }    

    #main-content ul li {
        background: url('{% static 'images/icons/bullet_black.png' %}') center left no-repeat;
        padding: 4px 0 4px 20px;
    }
</style>
{% endblock css %}

{% block js %}
{{ block.super }}
<script>
    var submissions = Array();
    var types = Array();
    var samples = 0;
    var oTable;
    var giRedraw = false;
    var currentSelectedTr 
    var clickedNode     
    var asInitVals = new Array();

    $(document).ready(function() { 
        aSelected = $('#id_samples').val();
        aSelected = (aSelected == null)? []: aSelected.map(Number);

        oTable = $('table.samples').dataTable({    
                    "sScrollX": "100%",
                    "aaSorting": [[ 1, "desc" ]],
                    "aoColumnDefs": [
                        { "aTargets": [ 0 ], "bSortable": false,}
                    ],
                    "fnRowCallback": function( nRow, aData, iDisplayIndex ) {
                        var id = parseInt($("input", nRow).val());
                        if ( $.inArray(id, aSelected) !== -1 ) {
                            $(nRow).addClass('highlight');
                            $("input", nRow).attr("checked", true);
                        }
                    },
                    "fnDrawCallback": function( oSettings ) {
                        $("input[name='checkAll']").attr("checked", false);
                        $("input[type='checkbox'][name='sample_id']").change(function(event){
                            var id = parseInt($(this).val());
                            var index = $.inArray(id, aSelected);
                          
                            if (index === -1 && $(this).is(":checked")) {
                                $(this).parent().parent().addClass('highlight');
                                aSelected.push( id );
                            } else if(index != -1 && !$(this).is(":checked")) {
                                $(this).parent().parent().removeClass('highlight');
                                aSelected.splice( index, 1 );
                            }
                           $("#total-samples").text(aSelected.length);
                        });
                    }
            });
            
        $('form').submit(function() {
            if(aSelected.length == 0){
                alert('Select at least one sample');
                return false;
            }
            $('#id_samples').val(aSelected);
        })

        $('thead input').keyup(function() {
            oTable.fnFilter( this.value, $("thead input").index(this) );
        });

        $("thead input").each( function (i) {
            asInitVals[i] = this.value;
        });

        $("thead input").focus( function () {
            if ( this.className == "search_init" )
            {
                $(this).removeClass("search_init");
                this.value = "";
            }
        });

        $("thead input").blur( function (i) {
            if ( this.value == "" )
            {
                $(this).addClass("search_init");
                this.value = asInitVals[$("thead input").index(this)];
            }
        });

        $('#id_prep_type').change( function() { 
            aSelected = []
            oTable.$("tr.highlight")
                 .each(function(index) {
                     $('input[type="checkbox"]', this).attr('checked', false);
                     $(this).removeClass('highlight');
                 })
            oTable.fnFilter( $('option:selected', this).text() )
            $("#total-samples").text(0);
        });

        $("input[name='checkAll']").change(function(){
            $("input[type='checkbox'][name='sample_id']").attr("checked", $(this).is(":checked")).change(); 
        });

    });    
    
</script>
{% endblock js %}

{% block content %}
    {% if project %}
        <h2>Project {{ project.id }}</h2>
    {% else %}
        <h2>Start a Project</h2>
        <p>To start a new project:
            <ul>
                <li>Click on the individual samples below (clicking on submissions coming soon):</li>
                <li>Click on "Start Project"</li>
            </ul>
        </p>
    {% endif %}
    <form action="" method="post">{% csrf_token %}
    {{ form }}
        <div class="content-box">
            <div class="content-box-header">
                <h3>Select Samples (<span id="total-samples"></span>)</h3>
            </div>
            <div class="content-box-content">
                <table class="samples">
                    <thead>
                        <tr>
                            <th>All</th>
                            <th>GTAC ID</th>
                            <th>Sample</th>
                            <th>Submitted</th>
                            <th>Prep Type</th>
                            <th>Client</th>
                        </tr>
                        <tr>
                            <th><input type="checkbox" name="checkAll" /></th>
                            <th><input type="text" value="Search GTAC ID" class="search_init"/></th>
                            <th><input type="text" value="Search Sample" class="search_init"/></th>
                            <th><input type="text" value="Search Submitted" class="search_init"/></th>
                            <th><input type="text" value="Search Prep Types" class="search_init"/></th>
                            <th><input type="text" value="Search Client" class="search_init"/></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for spd in form.fields.samples.queryset.all %}
                        <tr data-type="{{ spd.preptype }}" data-spd="{{ spd.id }}" data-sub="{{ spd.sample.submission.id }}">
                            <td><input type="checkbox" id="sample_{{spd.id}}" name="sample_id" value="{{ spd.id }}"></td>
                            <td>{{ spd.sample.specimen.gtac_id }}</td>
                            <td>{{ spd.sample.specimen.name }}</td>
                            <td>{{ spd.sample.submission.submitted|date:"m/d/Y" }}</td>
                            <td>{{ spd.sample.submission.sample_set.all.0.libprep.preptype }}</td>
                            <td>{{ spd.sample.submission.client.name }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                
                <input type="submit" class="button" value="{% if project%} Add samples {% else %}Start Project{% endif %}" />
                {% if project%} <a href="{%  url 'libprep.views.project_detail' project.id %}" class="button">Cancel</a> {% endif %}
            </div>
        </div>
    </form>
{% endblock content %}

theme/templates/libprep/project-prep-data-form.html
{% if def.type == 'STR' %}<input type="text" value="{% if value %}{{ value }}{% endif %}">
{% else %}
    {% if def.type == 'IMAGE' %}
    {{ def.label }}: <input type="file" value="{% if value %}{{ value }}{% endif %}">
    {% endif %}
{% endif %}

theme/templates/libprep/sample-browse.html
{% extends "frontend/base.html" %}

{% block js %}
{{ block.super }}
<script type="text/javascript">
$(function() {
  $('#sample tbody tr').formset();
  $('table').dataTable({
    "bServerSide": true,
    "sAjaxSource": "",
    'bStateSave': true
  });
});
</script>
{% endblock js %}

{% block content %}
<h1>Browse Submissions</h1>
<table>
<thead>
<tr>
<th>Name</th>
<th>Client</th>
<th>Submitted</th>
</tr>
</thead>
<tbody>
</tbody>
<tfoot></tfoot>
</table>
{% endblock content %}

theme/templates/libprep/submission-assign.html
{% extends "frontend/base.html" %}

{% block extrajs %}
<script type="text/javascript">
$(function() {
  //$('tbody tr').formset();
  $('table').dataTable({
    /*"bServerSide": true,
    "sAjaxSource": "",
    'bStateSave': true*/
  });
});
</script>
{% endblock extrajs %}

{% block content %}
<h1>New Submissions</h1>
<form action="{% url libprep-submission-assign %}" method="post">{% csrf_token %}
{{ formset.management_form }}
<table>
<thead>
<tr>
<th>Submission ID#</th>
<th># Samples</th>
<th>Client</th>
<th>Prep Type</th>
<th>Submitted</th>
<th>Take Ownership</th>
</tr>
</thead>
<tbody>
{% for f in formset %}
{% with f.instance as s %}
<tr>
<td>{{ f.id }}{{ s.id }}</td>
<td>{{ s.samplesubmission_set.count }}</td>
<td>{{ s.client.name }}</td>
<td>{{ s.samplesubmission_set.all.0.libprep.preptype }}</td>
<td>{{ s.submitted }}</td>
<td>{{ f.assigned }}</td>
</tr>
{% endwith %}
{% endfor %}
</tbody>
<tfoot></tfoot>
</table>
<input type="submit">
</form>
{% endblock content %}